version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.2
    - 10.1.3
  - dependency-name: aws-amplify-react
    versions:
    - 3.1.3
    - 4.2.27
  - dependency-name: husky
    versions:
    - 4.3.6
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: prettier-eslint-cli
    versions:
    - 5.0.0
  - dependency-name: handlebars
    versions:
    - 4.7.6
