# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-amplify-react
      - build

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
            - packages/hardchor-scipts/node_modules
            - packages/serverless-appsync/node_modules
            - packages/nextjs/node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn test

  build-amplify-react:
    docker:
      - image: circleci/node:10.15
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            - v2-dependencies-
      - run: yarn workspace @monorepo/amplify-react install
      - save_cache:
          paths:
            - node_modules
            - packages/amplify-react/node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}
      - run: yarn workspace @monorepo/amplify-react test
