# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.16

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-amplify-react
      - build

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: yarn workspace @hardchor/scripts install --prod --frozen-lockfile
      - run: yarn install --frozen-lockfile

      - save_cache:
          paths:
            - node_modules
            - packages/hardchor-scipts/node_modules
            - packages/serverless-appsync/node_modules
            - packages/nextjs/node_modules
          key: v2-dependencies-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn test --stream ----ignore @hardchor/amplify-react

  build-amplify-react:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo
    steps:
      - checkout
      - aws-cli/setup:
          profile-name: default
      - restore_cache:
          keys:
            - v1-amplify-react-dependencies-{{ checksum "yarn.lock" }}
            - v1-amplify-react-dependencies-
      - run: yarn workspace @hardchor/scripts install --prod --frozen-lockfile
      - run: yarn workspace @hardchor/amplify-react install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
            - packages/amplify-react/node_modules
          key: v1-amplify-react-dependencies-{{ checksum "yarn.lock" }}
      - run:
          name: 'Checkout Amplify test Environment'
          command: |
            yarn workspace @hardchor/amplify-react amplify env list
            yarn workspace @hardchor/amplify-react amplify init --amplify "{\"envName\":\"test\"}" --providers "{\"awscloudformation\":{\"useProfile\":true,\"profileName\":\"default\"}}" --yes
      - run:
          name: 'Deploy to test'
          command: |
            yarn workspace @hardchor/amplify-react amplify publish --invalidateCloudFront --codegen "{\"generateCode\":false}" -- yes
      - run: yarn workspace @hardchor/amplify-react test
