projects:
  amplifyreact:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        graphQLApiId: d4x3b2jtbzhdporuwf4mbqgyma
      endpoints:
        prod: >-
          https://lbfdf6hi7bb6jm6horwhpza5ey.appsync-api.eu-west-1.amazonaws.com/graphql
