projects:
  amplifyreact:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        graphQLApiId: 5lzqtchbcbd2dcqydxmbsk4lre
      endpoints:
        prod: >-
          https://bhhynfo4bvcwpjr4a3jwplohyq.appsync-api.eu-west-1.amazonaws.com/graphql
